package orchestration

import (
	"fmt"
	"path/filepath"
	"strings"
)

// chatConversationNote is the static transcript-layout explanation that rides
// in the chat system prompt (spec 19 P4). It must contain nothing that varies
// per chat or per turn — it sits inside the system param under the ladder's
// BP1 breakpoint, so any change to it cold-busts every open chat's cache.
const chatConversationNote = `
<conversation_note>
This is a multi-turn conversation. Completed turns appear as <turn> elements
in order. Focus on the final turn marked status="awaiting_response" - that is
the message requiring your reply. The respond_as attribute indicates what
persona to use. Previous responses may have been generated by different
prompts or personas; interpret and continue through YOUR current system
instructions.
</conversation_note>
`

// buildChatSystemPrompt assembles the chat-lifetime system region: the chat
// template wrapped in <system_instructions> plus the static conversation
// note. Under the Anthropic ladder it travels as the API system param with
// BP1 (spec 19 D7); byte-stable for the whole chat as long as the turn
// template doesn't change.
func buildChatSystemPrompt(templateContent []byte) string {
	var sb strings.Builder
	sb.WriteString("<system_instructions>\n")
	sb.Write(templateContent)
	sb.WriteString("\n</system_instructions>\n")
	sb.WriteString(chatConversationNote)
	return sb.String()
}

// buildChatContextBlock renders the per-turn <context> section: inlined
// dependency bodies and markers describing the separately uploaded files.
// Returns "" when there is nothing to describe. This block belongs to the
// VOLATILE prompt region — see the transcript-split comment in
// executeChatJob for why it must not live in system or ahead of the history
// blocks.
func buildChatContextBlock(
	prependedDependencies []struct {
		Filename string
		Content  string
	},
	dependencyFilePaths, includeFilePaths, contextFilePaths []string,
) string {
	if len(prependedDependencies) == 0 && len(dependencyFilePaths) == 0 && len(includeFilePaths) == 0 && len(contextFilePaths) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("<context>\n")

	// Prepended dependencies (inlined content from upstream jobs).
	for _, dep := range prependedDependencies {
		sb.WriteString(fmt.Sprintf("    <prepended_dependency file=\"%s\">\n", dep.Filename))
		sb.WriteString(dep.Content)
		sb.WriteString("\n    </prepended_dependency>\n")
	}

	// Uploaded dependencies (references to files uploaded separately).
	for _, depPath := range dependencyFilePaths {
		sb.WriteString(fmt.Sprintf("    <uploaded_context_file file=\"%s\" type=\"dependency\" importance=\"high\" description=\"Context from upstream jobs in this LLM pipeline.\"/>\n", filepath.Base(depPath)))
	}

	// Include files (explicitly included files for this task).
	for _, includePath := range includeFilePaths {
		sb.WriteString(fmt.Sprintf("    <uploaded_context_file file=\"%s\" type=\"include\" importance=\"high\" description=\"File explicitly included for this task.\"/>\n", filepath.Base(includePath)))
	}

	// Context files (concatenated project/source code).
	for _, ctxPath := range contextFilePaths {
		sb.WriteString(fmt.Sprintf("    <uploaded_context_file file=\"%s\" type=\"repository\" importance=\"medium\" description=\"Concatenated project/source code files from the current repository.\"/>\n", filepath.Base(ctxPath)))
	}

	sb.WriteString("</context>\n")
	return sb.String()
}

// flattenChatPrompt joins the three chat regions (system, history blocks,
// volatile turn) into the single-prompt form used by providers without a
// block-structured upload — gemini keeps its flat upload (spec 19 scenario
// 20), the mock LLM client just needs a prompt string, and the briefing file
// records the whole payload for observability.
func flattenChatPrompt(systemPrompt string, historyBlocks []string, volatilePrompt string) string {
	var sb strings.Builder
	sb.WriteString("<prompt>\n")
	sb.WriteString(systemPrompt)
	sb.WriteString("\n")
	for _, h := range historyBlocks {
		sb.WriteString(h)
	}
	sb.WriteString(volatilePrompt)
	sb.WriteString("</prompt>\n")
	return sb.String()
}
