#!/bin/sh
# Entrypoint for mock agent container

# Install required packages
apk add --no-cache bash git

# Create mock grove binary
cat > /usr/local/bin/grove << 'GROVEEOF'
#!/bin/sh
# Mock grove binary for orchestration demo

if [ "$1" = "agent" ]; then
    shift  # Remove "agent" from arguments
    
    echo "🤖 Mock Grove Agent v1.0"
    echo "Working directory: $(pwd)"
    echo ""
    
    # Read prompt from stdin
    prompt=$(cat)
    
    echo "📝 Processing prompt..."
    echo ""
    
    # Simulate some work based on prompt content
    if echo "$prompt" | grep -q "implement"; then
        # Create a mock implementation file
        cat > implementation.py << 'PYEOF'
# Generated by Mock Grove Agent
# This simulates what a real agent would produce

def authenticate_user(username, password):
    """Mock authentication function."""
    # In a real implementation, this would check credentials
    return True

def generate_token(user_id):
    """Mock token generation."""
    # In a real implementation, this would create a JWT
    return "mock-jwt-token-" + str(user_id)

class AuthenticationService:
    """Mock authentication service."""
    
    def __init__(self):
        self.users = {}
    
    def register(self, username, password):
        """Register a new user."""
        if username not in self.users:
            self.users[username] = {"password": password}
            return True
        return False
    
    def login(self, username, password):
        """Authenticate a user."""
        if username in self.users and self.users[username]["password"] == password:
            return generate_token(username)
        return None

# Example usage
if __name__ == "__main__":
    service = AuthenticationService()
    print("Mock Authentication Service initialized")
PYEOF
        echo "✅ Created implementation.py"
    fi
    
    # Always exit successfully to simulate successful agent run
    echo ""
    echo "✨ Mock agent completed successfully"
    exit 0
else
    echo "Error: Mock grove only supports 'agent' command"
    exit 1
fi
GROVEEOF

chmod +x /usr/local/bin/grove

# Keep container running
exec sleep infinity