#!/bin/bash
# Mock grove agent for orchestration demo
# This simulates the grove agent behavior without requiring the real Claude binary

echo "🤖 Mock Grove Agent (Demo Mode)"
echo "Working directory: $(pwd)"
echo ""

# Read prompt from stdin
prompt=$(cat)

echo "📝 Received prompt:"
echo "$prompt"
echo ""

# Simulate processing
sleep 1

# Create some mock output based on the prompt
if echo "$prompt" | grep -i "implement\|carry out\|plan" > /dev/null; then
    # Create a mock implementation file
    cat > implementation.py << 'EOF'
# Generated by Mock Grove Agent
# This is a demonstration of orchestration

class FeatureImplementation:
    """Mock implementation generated by the agent."""
    
    def __init__(self):
        self.config = {}
        self.initialized = True
    
    def process_request(self, request):
        """Process incoming requests."""
        # Mock processing logic
        return {"status": "success", "data": request}
    
    def validate_input(self, data):
        """Validate input data."""
        if not data:
            raise ValueError("Input data cannot be empty")
        return True

# Example usage
if __name__ == "__main__":
    feature = FeatureImplementation()
    result = feature.process_request({"test": "data"})
    print(f"Processed: {result}")
EOF
    
    echo "✅ Created implementation.py"
    echo ""
    
    # Create a test file too
    cat > test_implementation.py << 'EOF'
# Test file generated by Mock Grove Agent
import unittest
from implementation import FeatureImplementation

class TestFeatureImplementation(unittest.TestCase):
    def setUp(self):
        self.feature = FeatureImplementation()
    
    def test_initialization(self):
        self.assertTrue(self.feature.initialized)
    
    def test_process_request(self):
        result = self.feature.process_request({"test": "data"})
        self.assertEqual(result["status"], "success")

if __name__ == "__main__":
    unittest.main()
EOF
    
    echo "✅ Created test_implementation.py"
fi

echo ""
echo "✨ Mock agent completed successfully"
exit 0