package review_packet

import (
	"fmt"
	"sort"
	"strings"

	"github.com/grovetools/flow/pkg/orchestration"
	"github.com/grovetools/flow/pkg/planops"
)

// Render produces the packet note's machine-owned body — everything that goes
// ABOVE nb's sync marker. It is pure: same Packet in, same bytes out, no
// filesystem, git or notebook access. That purity is what makes the refresh
// idempotent, because the writer can re-render a packet with the previous
// note's timestamp and compare the result to what is on disk.
//
// Checklists render as markdown task lists on purpose. They are already the
// shape a forge PR body wants, so when outward projection lands it can lift
// this section verbatim instead of inventing a second renderer.
func Render(p Packet) string {
	var b strings.Builder

	fmt.Fprintf(&b, "<!-- %s schema_version=%d snapshot_schema_version=%d plan=%s worktree=%s -->\n\n",
		packetMarker, PacketSchemaVersion, SnapshotSchemaVersion, p.Plan, p.Worktree)

	fmt.Fprintf(&b, "# %s\n\n", Title(p.Plan))
	b.WriteString("_Generated by `flow plan review` and refreshed at finish. Everything above the\n")
	b.WriteString("sync marker is rewritten on every refresh; write notes BELOW the marker._\n\n")

	renderHeader(&b, p)
	renderReviewState(&b, p)
	renderChecklists(&b, p)
	renderScope(&b, p)
	renderDisposition(&b, p)
	renderLinks(&b, p)

	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderHeader(b *strings.Builder, p Packet) {
	fmt.Fprintf(b, "- **Plan:** %s\n", p.Plan)
	if p.Worktree != "" {
		fmt.Fprintf(b, "- **Worktree:** %s\n", p.Worktree)
	}
	if p.ContainerPath != "" {
		fmt.Fprintf(b, "- **Container:** `%s`\n", p.ContainerPath)
	}
	if len(p.Repos) > 0 {
		fmt.Fprintf(b, "- **Repos:** %s\n", strings.Join(p.Repos, ", "))
	}
	if p.Status != "" {
		fmt.Fprintf(b, "- **Plan status:** %s\n", p.Status)
	}
	fmt.Fprintf(b, "- **Checkpointed:** %s (%s)\n", p.Snapshot.CheckpointedAt, cell(p.Source))
	b.WriteString("\n")
}

// renderReviewState is the section the packet exists for: who reviewed what, at
// which blob hash, and whether it has changed since.
func renderReviewState(b *strings.Builder, p Packet) {
	b.WriteString("## Review state\n\n")
	if p.SnapshotErr != "" {
		fmt.Fprintf(b, "_Partial checkpoint: %s_\n\n", p.SnapshotErr)
	}
	if !p.Snapshot.Available {
		b.WriteString("_No worktree registry entry for this plan — live review state could not be read._\n\n")
		return
	}
	if len(p.Snapshot.Files) == 0 {
		b.WriteString("_No files have been marked reviewed._\n\n")
		return
	}

	fmt.Fprintf(b, "%d of %d file(s) reviewed at their current content.\n\n",
		p.Snapshot.ReviewedCount(), len(p.Snapshot.Files))
	b.WriteString("| repo | file | state | reviewed at blob |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, f := range p.Snapshot.Files {
		fmt.Fprintf(b, "| %s | `%s` | %s | `%s` |\n",
			cell(f.Repo), cell(f.Path), stateLabel(f.State), shortSHA(f.LastReviewedBlob))
	}
	b.WriteString("\n")
}

// stateLabel renders a derived review state for humans. The glyphs mirror
// git-viewer's Changes page so the packet reads the same way the TUI does.
func stateLabel(state string) string {
	switch state {
	case StateReviewedCurrent:
		return "✓ reviewed"
	case StateChangedSinceReview:
		return "Δ changed since review"
	default:
		return "? unknown"
	}
}

func renderChecklists(b *strings.Builder, p Packet) {
	if len(p.Snapshot.Checklists) == 0 {
		return
	}
	b.WriteString("## Checklists\n\n")
	for _, cl := range p.Snapshot.Checklists {
		title := cl.Title
		if title == "" {
			title = cl.ID
		}
		fmt.Fprintf(b, "### %s", title)
		done := 0
		for _, it := range cl.Items {
			if it.Checked {
				done++
			}
		}
		fmt.Fprintf(b, " (%d/%d)\n\n", done, len(cl.Items))
		if cl.Agent != "" {
			fmt.Fprintf(b, "_Recorded by %s._\n\n", cl.Agent)
		}
		if len(cl.Items) == 0 {
			b.WriteString("_No items._\n\n")
			continue
		}
		for _, it := range cl.Items {
			mark := " "
			if it.Checked {
				mark = "x"
			}
			fmt.Fprintf(b, "- [%s] %s\n", mark, it.Text)
			if note := strings.TrimSpace(it.Note); note != "" {
				fmt.Fprintf(b, "  - %s\n", strings.ReplaceAll(note, "\n", " "))
			}
		}
		b.WriteString("\n")
	}
}

// renderScope is what this plan actually changed, per job and per repo, from
// the commits.json sidecars each job writes.
func renderScope(b *strings.Builder, p Packet) {
	b.WriteString("## Scope\n\n")
	if len(p.Jobs) == 0 {
		b.WriteString("_No jobs in this plan._\n\n")
		return
	}
	var rows []string
	for _, job := range p.Jobs {
		if job.Record == nil {
			continue
		}
		repos := append([]orchestration.JobCommitsRepo(nil), job.Record.Repos...)
		sort.SliceStable(repos, func(i, j int) bool { return repos[i].Name < repos[j].Name })
		for _, repo := range repos {
			// A captured range that produced nothing is not worth a row. A NIL
			// Commits is different — it is commits.json's contractual "could
			// not be computed", and rendering it as 0 would assert the job
			// produced nothing, which is a claim nobody verified. It gets a
			// row, marked n/a.
			if repo.Commits != nil && len(repo.Commits) == 0 {
				continue
			}
			count := "n/a"
			if repo.Commits != nil {
				count = fmt.Sprintf("%d", len(repo.Commits))
			}
			rows = append(rows, fmt.Sprintf("| %s | %s | %s | `%s..%s` | %s |\n",
				cell(job.JobFile), cell(repo.Name), cell(repo.Branch),
				shortSHA(repo.StartHead), shortSHA(repo.EndHead), count))
		}
	}

	if len(rows) == 0 {
		b.WriteString("_No job recorded a commit range._\n\n")
	} else {
		b.WriteString("| job | repo | branch | range | commits |\n")
		b.WriteString("| --- | --- | --- | --- | --- |\n")
		for _, row := range rows {
			b.WriteString(row)
		}
		b.WriteString("\n")
	}

	for _, job := range p.Jobs {
		if job.Err != "" {
			fmt.Fprintf(b, "_Commit capture unreadable for %s: %s_\n\n", cell(job.JobFile), job.Err)
		}
	}
}

// renderDisposition is where the plan stands against its base branch right now
// — the read-only planops preview, the same preflight `flow plan land` gates on.
func renderDisposition(b *strings.Builder, p Packet) {
	b.WriteString("## Disposition\n\n")
	if p.Preview == nil {
		reason := p.PreviewErr
		if reason == "" {
			reason = "not computed"
		}
		fmt.Fprintf(b, "_Could not preflight the worktree: %s_\n\n", reason)
		return
	}
	if len(p.Preview.Repos) == 0 {
		b.WriteString("_No repository checkouts to inspect._\n\n")
		return
	}
	b.WriteString("| repo | branch | onto | ahead | behind | dirty | disposition | reason |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")
	repos := append([]planops.RepoPreview(nil), p.Preview.Repos...)
	sort.SliceStable(repos, func(i, j int) bool { return repos[i].Name < repos[j].Name })
	for _, repo := range repos {
		fmt.Fprintf(b, "| %s | %s | %s | %d | %d | %s | %s | %s |\n",
			cell(repo.Name), cell(repo.Branch), cell(repo.Onto),
			repo.Ahead, repo.Behind, yesNo(repo.Dirty),
			cell(string(repo.Disposition)), cell(repo.Reason))
	}
	b.WriteString("\n")
}

func renderLinks(b *strings.Builder, p Packet) {
	b.WriteString("## Links\n\n")
	fmt.Fprintf(b, "- **plan_ref:** `%s`\n", p.PlanRef)
	if p.TicketsErr != "" {
		fmt.Fprintf(b, "- _Linked notes unreadable: %s_\n", p.TicketsErr)
	}
	for _, t := range p.Tickets {
		label := t.Title
		if label == "" {
			label = t.Path
		}
		fmt.Fprintf(b, "- %s — `%s`", cell(label), t.Path)
		if t.PlanJob != "" {
			fmt.Fprintf(b, " (job %s)", t.PlanJob)
		}
		b.WriteString("\n")
	}
	if len(p.Tickets) == 0 && p.TicketsErr == "" {
		b.WriteString("- _No other notes are linked to this plan._\n")
	}
	b.WriteString("\n")
}

func cell(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "—"
	}
	// Pipes would break the markdown table row this lands in.
	return strings.ReplaceAll(s, "|", "\\|")
}

func shortSHA(sha string) string {
	sha = strings.TrimSpace(sha)
	if sha == "" {
		return "—"
	}
	if len(sha) > 12 {
		return sha[:12]
	}
	return sha
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}
